# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BurdenSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, verbose_name='\u6458\u8981')),
                ('total_amount', models.FloatField(verbose_name='\u6295\u6599\u603b\u91cf')),
                ('total_payable', models.FloatField(verbose_name='\u5e94\u4ed8\u5408\u8ba1')),
                ('total_discount', models.FloatField(verbose_name='\u6298\u6263\u5408\u8ba1')),
                ('date', models.DateField(verbose_name='\u751f\u4ea7\u65e5\u671f')),
                ('time_stamp', models.DateTimeField(verbose_name='time stamp')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='\u59d3\u540d')),
            ],
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='\u91cd\u91cf')),
                ('price', models.FloatField(verbose_name='\u5355\u4ef7')),
                ('discount', models.FloatField(verbose_name='\u6298\u6263')),
                ('account_payable', models.FloatField(verbose_name='\u5e94\u4ed8\u6b3e')),
                ('burden_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.BurdenSheet')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountant.ProductName')),
            ],
        ),
        migrations.AddField(
            model_name='burdensheet',
            name='customer',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='accountant.Customer'),
        ),
    ]
