# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='\u91cd\u91cf')),
            ],
        ),
        migrations.AlterField(
            model_name='burdensheet',
            name='customer',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='accountant.Customer', verbose_name='\u5ba2\u6237'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountant.ProductName', verbose_name='\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='burden_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.BurdenSheet'),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountant.ProductName', verbose_name='\u540d\u79f0'),
        ),
    ]
