# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0002_auto_20170602_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burdensheet',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time stamp'),
        ),
    ]
