# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 03:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0004_auto_20170603_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='\u751f\u4ea7\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='burdensheet',
            name='total_discount',
            field=models.FloatField(default=0, verbose_name='\u6298\u6263\u5408\u8ba1'),
        ),
    ]
