# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 07:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0005_auto_20170604_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='\u91cd\u91cf')),
                ('price', models.FloatField(verbose_name='\u5355\u4ef7')),
                ('discount', models.FloatField(verbose_name='\u4f18\u60e0')),
                ('account_payable', models.FloatField(verbose_name='\u5e94\u4ed8\u6b3e')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='\u8d2d\u4e70\u65e5\u671f')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountant.ProductName', verbose_name='\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='\u59d3\u540d')),
            ],
        ),
        migrations.AlterField(
            model_name='productorder',
            name='account_payable',
            field=models.FloatField(verbose_name='\u5e94\u6536\u6b3e'),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.Source', verbose_name='\u8fdb\u8d27\u6e90'),
        ),
    ]
