# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 01:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0008_remove_burdensheet_total_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='\u6458\u8981')),
                ('amount', models.FloatField(verbose_name='\u91cd\u91cf')),
                ('price', models.FloatField(verbose_name='\u5355\u4ef7')),
                ('account_payable', models.FloatField(verbose_name='\u5e94\u6536\u6b3e')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='\u751f\u4ea7\u65e5\u671f')),
                ('burden_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.BurdenSheet')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='\u79cd\u7c7b')),
            ],
        ),
        migrations.AddField(
            model_name='processingfee',
            name='processing_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.ProcessingType', verbose_name='\u79cd\u7c7b'),
        ),
    ]
