# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0010_auto_20170606_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Payee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountant.Payee', verbose_name='\u6536\u6b3e\u4eba/\u7528\u9014'),
        ),
        migrations.AlterField(
            model_name='payee',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u6536\u6b3e\u4eba/\u7528\u9014'),
        ),
    ]
