# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0011_auto_20170606_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burdensheet',
            name='customer',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='accountant.Payer', verbose_name='\u5ba2\u6237'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
