# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0012_auto_20170606_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProductName',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='\u540d\u79f0')),
            ],
        ),
        migrations.AlterField(
            model_name='customerproduct',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountant.CustomerProductName', verbose_name='\u540d\u79f0'),
        ),
    ]
