# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0013_auto_20170606_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='\u8d26\u6237')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountant.Account', verbose_name='\u4ed8\u6b3e\u8d26\u6237'),
        ),
        migrations.AddField(
            model_name='income',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountant.Account', verbose_name='\u6536\u6b3e\u8d26\u6237'),
        ),
    ]
