# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text2',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
